ALTER TABLE IF EXISTS changes ADD COLUMN IF NOT EXISTS modification TEXT;

ALTER TABLE IF EXISTS changes DROP COLUMN IF EXISTS old_value;
ALTER TABLE IF EXISTS changes DROP COLUMN IF EXISTS new_value;