ALTER TABLE IF EXISTS changes ADD COLUMN IF NOT EXISTS old_value TEXT;
ALTER TABLE IF EXISTS changes ADD COLUMN IF NOT EXISTS new_value TEXT;

ALTER TABLE IF EXISTS changes DROP COLUMN IF EXISTS modification;