 CREATE TABLE IF NOT EXISTS collections (
           id TEXT PRIMARY KEY,
           name TEXT NOT NULL,
           first_seen TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
           last_seen TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
 );